spring: 
  
  profiles.active: ssl

logging:
  level: 
    root: WARN
    org.springframework.web: INFO
    com.andrewfesta.doublesolitare: DEBUG
#    com.andrewfesta.doublesolitare.controller: TRACE
    GameLog: DEBUG
  file: logs/double-solitare.log
  
---
spring:
  profiles: ssl
  
server:
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
  ssl:
    key-store: ${KEYSTORE_FILE}
    key-store-type: ${KEYSTORE_TYPE}
    key-password: ${KEYSTORE_PASS} 
    key-alias: ${KEYSTORE_ALIAS}