---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
    # Use "doctl compute certificate list" to get this ID
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: “a2e2e86d-45e7-43bd-a8e4-637937810fc7”
spec:
  clusterIP: 10.245.24.137
  externalTrafficPolicy: Local
  healthCheckNodePort: 32131
  ports:
  - name: http
    nodePort: 31634
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 30644
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  use-forwarded-headers: "true"
  compute-full-forwarded-for: "true"
  use-proxy-protocol: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solitare-deploy
  namespace: andrewfesta
  labels:
    app: solitare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solitare
  strategy: {}
  template:
    metadata:
      labels:
        app: solitare
    spec:
      containers:
      - image: apfesta/double-solitare:%VERSION%
        name: solitare
        ports:
        - containerPort: 8080
        resources: {}
        env:
        - name: SPRING_OPTS
          value: "--spring.profiles.active=none --server.port=8080"
      imagePullSecrets:
      - name: dockerhub
---
apiVersion: v1
kind: Service
metadata:
  name: solitare-svc
  namespace: andrewfesta
  labels:
    app: solitare
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: solitare
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: solitare-ingress
  namespace: andrewfesta
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  tls:
  - hosts:
    - solitare.andrewfesta.com
    secretName: solitare-tls
  rules:
  - host: solitare.andrewfesta.com
    http:
      paths:
      - path: /
        backend:
          serviceName: solitare-svc
          servicePort: 80
