apiVersion: apps/v1
kind: Deployment
metadata:
  name: solitare-deploy
  namespace: andrewfesta
  labels:
    app: solitare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solitare
  strategy: {}
  template:
    metadata:
      labels:
        app: solitare
    spec:
      containers:
      - image: apfesta/double-solitare:latest
        name: solitare
        ports:
        - containerPort: 8080
        resources: {}
        env:
        - name: SPRING_OPTS
          value: "--spring.profiles.active=none --server.port=8080"
      imagePullSecrets:
      - name: dockerhub
---
apiVersion: v1
kind: Service
metadata:
  name: solitare-svc
  namespace: andrewfesta
  labels:
    app: solitare
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: solitare
